# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task default: :spec

task :generate_rbs do
  sh "sord sig/defs.rbs"
  sh %Q{sed -i#{" " if RUBY_PLATFORM.include?("darwin")}'' '1s/^/# This file was generated by "rake generate_rbs"\\n\\n/' sig/defs.rbs}
  # Workaround for the error "Detected recursive ancestors: ::SocksHandler::UDPSocket < ::SocksHandler::UDPSocket"
  sh %Q{sed -i#{" " if RUBY_PLATFORM.include?("darwin")}'' 's/UDPSocket < UDPSocket/UDPSocket < ::UDPSocket/' sig/defs.rbs}
end
