# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

task default: :spec

task :generate_rbs do
  sh "sord sig/defs.rbs"
  sh %Q{sed -i#{" " if RUBY_PLATFORM.include?("darwin")}'' '1s/^/# This file was generated by "rake generate_rbs"\\n/' sig/defs.rbs}
end
