name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - "3.0"
          # Net::HTTP in Ruby 3.1.2 uses Socket.tcp instead of TCPSocket.new
          # cf. https://github.com/ruby/net-http/pull/74
          - "3.1.2"
          - "3.1"
          - "3.2"

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Check if defs.rbs is up-to-date
      run: bundle exec rake generate_rbs && git diff --exit-code
    - name: Run the default task
      run: |
        docker compose up -d
        RUBYOPT='-rbundler/setup -rrbs/test/setup' RBS_TEST_TARGET='SocksHandler::*' bundle exec rake
